version: '3.9'
services:
  homebridge:
    image: homebridge/homebridge
    container_name: Homebridge
    healthcheck:
     test: curl -f http://localhost:8581/ || exit 1
    mem_limit: 8g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: always
    volumes:
      - /volume1/docker/homebridge:/homebridge:rw
    environment:
      - TZ=America/Chicago
      - PACKAGES=ffmpeg
    network_mode: host
