services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
    hostname: pihole

    environment:
      TZ: America/Chicago
      FTLCONF_webserver_api_password: ''
      FTLCONF_dns_listeningMode: all

    volumes:
      - /volume1/docker/pihole/etc-pihole:/etc/pihole
      - /volume1/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    networks:
      pihole_macvlan:
        ipv4_address: 192.168.10.250

    restart: unless-stopped

networks:
  pihole_macvlan:
    external: true
